### ISSUE TITLE
单纯的对指令无响应

### ISSUE THREAD

**Issue by satisl** [kifuan/nonebot-plugin-gpt#1]
我敢保证我仔细按照每一步配置了，但还是无效
pip下载
![1670321062415](https://user-images.githubusercontent.com/116792223/205880902-fa07718f-3695-4fe3-8080-055705e0e9ee.jpg)
.env配置
![image](https://user-images.githubusercontent.com/116792223/205881108-0c85a065-1923-4f0d-87dd-992d2815a77a.png)
使用

![205882862-7c111980-d3c4-4f07-92d7-6b9c63827f0b](https://user-images.githubusercontent.com/116792223/205885736-36e829b9-70a5-4f28-8aaa-e05149d4faaf.png)

**Comment by kifuan** [comment]
这个插件的版本呢

**Comment by kifuan** [comment]
请更新一下看看是否还有问题

```
pip install --upgrade nonebot-plugin-gpt
```

**Comment by satisl** [comment]
![image](https://user-images.githubusercontent.com/116792223/205884502-d78752fc-725a-4878-a0c2-1d05e25a625c.png)

**Comment by kifuan** [comment]
你确定更新了吗，在命令行里运行啊

**Comment by kifuan** [comment]
我刚才新建了一个项目，除了

```py
nonebot.load_plugin('nonebot_plugin_gpt')
```

什么都没写，我这里是正常的，要不你建一个新项目测试一下？

**Comment by satisl** [comment]
![image](https://user-images.githubusercontent.com/116792223/205886816-6983ff8a-8720-41bd-a99b-b1a09f05672c.png)
在bot.py加上这条?
![image](https://user-images.githubusercontent.com/116792223/205886960-5a742b79-72a9-4988-878c-1214fba66102.png)
报错

**Comment by kifuan** [comment]
呃，我不清楚你是怎么引入的这个插件

**Comment by kifuan** [comment]
之前是怎么办的

**Comment by satisl** [comment]
![image](https://user-images.githubusercontent.com/116792223/205887477-f879d3fc-ccd0-470e-96c0-185a7403df44.png)
修改pyproject.toml

**Comment by kifuan** [comment]
你把pyproject里面的`nonebot_plugin_gpt`先删除，手动用nonebot.load_plugin试一下，我看看这是什么问题。

**Comment by satisl** [comment]
![image](https://user-images.githubusercontent.com/116792223/205887872-1420bc83-ccf6-44ef-acf2-263b43a03ba4.png)
已经删除测试了，仍然无效
![image](https://user-images.githubusercontent.com/116792223/205887995-1c29e13f-61db-4eda-8db0-7d00697c6962.png)

**Comment by kifuan** [comment]
呃，我测试了一下，我这里用什么加载方式都是可以的，要不你先关一下另外两个插件，看看是否是插件间存在冲突？

**Comment by kifuan** [comment]
还有一种可能，是网络请求的问题，你可以试试把下面这段代码粘贴至`bot.py`，看看是否会在控制台打印出ChatGPT给你的回复：

```py

@driver.on_startup
async def _():
    from nonebot_plugin_gpt.chatbot import Chatbot

    cb = await Chatbot.get_instance()
    async for line in cb.get_chat_lines(12345, 'hi'):
        print(line)
```

**Comment by satisl** [comment]
![image](https://user-images.githubusercontent.com/116792223/205892180-e6a9541f-cc3b-4ae9-830d-1267db1ed23f.png)
可以

**Comment by kifuan** [comment]
插件还是不能正常工作吗？

**Comment by satisl** [comment]
> 插件还是不能正常工作吗？

是的

**Comment by kifuan** [comment]
能否重新创建一个新项目，只引入这一个插件，看看是否还是有问题？

**Comment by satisl** [comment]
> 能否重新创建一个新项目，只引入这一个插件，看看是否还是有问题？

我在上面好像已经尝试过这种了，还是说在pyproject上只留有该插件？

**Comment by kifuan** [comment]
对，只留有这一个插件，看看能不能正常工作。

**Comment by satisl** [comment]
![image](https://user-images.githubusercontent.com/116792223/205894207-fc339f6b-1061-458b-81a9-a104150b2e0c.png)
![image](https://user-images.githubusercontent.com/116792223/205894303-a7c83b16-9be6-4bd6-bbe4-6eddee46038c.png)
![image](https://user-images.githubusercontent.com/116792223/205894379-3c29e6a4-a976-40a5-ba34-8fa217fbdf7c.png)
无效

**Comment by kifuan** [comment]
我不知道这到底是什么原因，我也不知道你的环境，我只是新建一个项目除了加载插件什么都没做它可以正常运行，我无法根据你提供的信息判断问题的原因。
![image](https://user-images.githubusercontent.com/61240774/205895254-0d79a4d9-a09f-49d0-a874-b6fbae35b205.png)

**Comment by kifuan** [comment]
我复现不了。

**Comment by satisl** [comment]
> 我不知道这到底是什么原因，我也不知道你的环境，我只是新建一个项目除了加载插件什么都没做它可以正常运行，我无法根据你提供的信息判断问题的原因。 ![image](https://user-images.githubusercontent.com/61240774/205895254-0d79a4d9-a09f-49d0-a874-b6fbae35b205.png)

debug是如何显示的？我这边好像从来没有，只有success,info,error

**Comment by kifuan** [comment]
![image](https://user-images.githubusercontent.com/61240774/205896664-62383ae0-bd44-4588-ab31-d8b9c42c7f8a.png)
![image](https://user-images.githubusercontent.com/61240774/205896747-45f333da-3776-4d61-b22a-e80779530c7d.png)

我即使用`poetry run`也照样正常运行，我不知道到底怎么复现这个bug。

**Comment by satisl** [comment]
> ![image](https://user-images.githubusercontent.com/61240774/205896664-62383ae0-bd44-4588-ab31-d8b9c42c7f8a.png) ![image](https://user-images.githubusercontent.com/61240774/205896747-45f333da-3776-4d61-b22a-e80779530c7d.png)
> 
> 我即使用`poetry run`也照样正常运行，我不知道到底怎么复现这个bug。

仔细查看了下，我的显示大致相同，但唯独缺少了debug

**Comment by satisl** [comment]
![image](https://user-images.githubusercontent.com/116792223/205897413-382fac06-f3a1-4bce-8018-2b9ecfa3febe.png)

**Comment by kifuan** [comment]
我大概猜到了，应该是版本问题，你运行一下这个。
```
py -3.10 -m poetry run pip install --upgrade nonebot-plugin-gpt
```

**Comment by satisl** [comment]
![image](https://user-images.githubusercontent.com/116792223/205899515-a57363b4-7d6d-47fe-9e81-9cb55654a6f9.png)
不行，他对/gpt毫无反应，反而对图片有所反应

**Comment by kifuan** [comment]
你能不能先不用poetry，直接敲`nb run`或者`py -3.10 -m nb-cli run`

**Comment by kifuan** [comment]
更正，nb_cli

**Comment by kifuan** [comment]
你能不能找到`nonebot_plugin_gpt`这个文件夹看看里面的`__init__.py`长什么样？

**Comment by satisl** [comment]
import random

from nonebot import on_command, on_regex, get_driver
from nonebot.adapters.onebot.v11.event import GroupMessageEvent
from .chatbot import Chatbot
from .config import gpt_config


driver = get_driver()
gpt = on_command('gpt')
control = on_command('gpt_control')
message = on_regex('^(?!/gpt)')


@driver.on_startup
async def _():
    # Initialize the bot.
    await Chatbot.get_instance()


@gpt.handle()
async def _(event: GroupMessageEvent):
    cb = await Chatbot.get_instance()
    text = event.get_message().extract_plain_text()
    async for line in cb.get_chat_lines(event.group_id, text):
        await gpt.send(line)


@control.handle()
async def _(event: GroupMessageEvent):
    if event.sender.user_id not in gpt_config.gpt_sudoers:
        await control.send('没有权限')
        return

    text = event.get_message().extract_plain_text()
    cb = await Chatbot.get_instance()

    if text == 'refresh_session':
        await cb.refresh_session()
        await control.send('刷新成功')
        return

    if text == 'reset_status':
        cb.reset_or_create_status(event.group_id)
        await control.send('重置成功')
        return

    await control.send('无效命令')


@message.handle()
async def _(event: GroupMessageEvent):
    if random.random() >= gpt_config.gpt_probability:
        return

    msg = event.get_message().extract_plain_text().strip()

    # Don't reply to empty messages.
    if msg == '':
        return

    cb = await Chatbot.get_instance()
    async for line in cb.get_chat_lines(event.group_id, msg):
        await message.send(line)

**Comment by kifuan** [comment]
这明明什么问题都没有啊，我。。。

**Comment by kifuan** [comment]
你把这个文件夹拖到自己目录下

**Comment by kifuan** [comment]
src/plugins

**Comment by satisl** [comment]
![image](https://user-images.githubusercontent.com/116792223/205904224-8b0db46b-96fd-4d94-a308-175256e32fd1.png)
这两个？

**Comment by kifuan** [comment]
上面的。

**Comment by satisl** [comment]
![image](https://user-images.githubusercontent.com/116792223/205905056-0e483064-339c-4dc8-9bd0-bc7dd8bd41db.png)
报错

**Comment by kifuan** [comment]
把plugins里边的nonebot_plugin_gpt删掉。

**Comment by satisl** [comment]
![image](https://user-images.githubusercontent.com/116792223/205906183-f5adf262-2114-4ae4-8181-c121d4072b17.png)
报错

**Comment by kifuan** [comment]
你就不能看看报错吗

**Comment by kifuan** [comment]
把我给你那一段删了啊

**Comment by satisl** [comment]
哦

**Comment by satisl** [comment]
![image](https://user-images.githubusercontent.com/116792223/205907061-58487a39-b84d-4fce-9879-092ab9212e7d.png)

**Comment by kifuan** [comment]
我真的无语了。
把这段粘贴到`bot.py`
```py
gpt = nonebot.on_command('gpt')

@gpt.handle()
async def _():
    await gpt.send('Fxxk world')
```

你看你输入 `/gpt` 它有反应吗。

**Comment by satisl** [comment]
![image](https://user-images.githubusercontent.com/116792223/205908825-5b9ca4a3-4870-4c1b-b646-e893e5ca169f.png)
/gpt无响应

**Comment by kifuan** [comment]
那你不打斜杠有反应吗

**Comment by satisl** [comment]
有了

**Comment by satisl** [comment]
![image](https://user-images.githubusercontent.com/116792223/205909222-30b243ba-8c0e-4954-8032-5779409e0900.png)

**Comment by kifuan** [comment]
。。。就这个问题折腾了一个小时

**Comment by satisl** [comment]
.....az，没想到是多了个/...

**Comment by kifuan** [comment]
我是怎么想都没想到问题出在默认配置上

**Comment by satisl** [comment]
幸苦了
