### ISSUE TITLE
nonebot导入chatgpt插件失败

### ISSUE THREAD

**Issue by baifagg** [kifuan/nonebot-plugin-gpt#2]
![image](https://user-images.githubusercontent.com/51266591/206105615-9c980d7b-9d66-4d14-b252-370a8bd745ef.png)

**Comment by kifuan** [comment]
```
nonebot.load_plugin('nonebot_plugin_gpt')
```

**Comment by baifagg** [comment]
![image](https://user-images.githubusercontent.com/51266591/206106232-7c225454-6f5a-4a79-9e87-7672cb336c92.png)
我把插件目录放在了bot.py文件目录下，运行时提示错误
![image](https://user-images.githubusercontent.com/51266591/206106381-3aeb4651-33b5-43c6-b25e-3f1bb59ae139.png)

**Comment by kifuan** [comment]
你这是引用了两边。

**Comment by baifagg** [comment]
![image](https://user-images.githubusercontent.com/51266591/206106735-fa2ca5ca-0c2e-488e-816a-f34baf17f474.png)
配置文件的格式有没有填对呢

**Comment by kifuan** [comment]
你能不能看一下nonebot的文档

**Comment by baifagg** [comment]
可以看一下配置文件的标准格式么 我刚接触这个，nonebot的文档也看了，不知道哪里出错

**Comment by kifuan** [comment]
呃，首先建议你用`pip install`，不要手动下载拖到你的文件夹里。

其次，配置文件要在`.env`文件里写，而不是直接编辑源代码。

**Comment by baifagg** [comment]
好的 谢谢 我试一下
