### ISSUE TITLE
返回的消息遇到\n似乎会分段发送？

### ISSUE THREAD

**Issue by Bearlele** [kifuan/nonebot-plugin-gpt#5]
假如让他写一段代码，他会分开很多段进行发送，请问如何让他能一次性发送完整？
![image](https://user-images.githubusercontent.com/30120610/206865835-1548c532-e401-49c1-8967-b1bd81c3c1b4.png)

**Comment by kifuan** [comment]
最开始设计这个的目的是防止发送单个消息太长，容易被风控，下个版本把这种处理方式换成发图片。

**Comment by kifuan** [comment]
现在超过一定限制会把文字转为图片了，这个问题解决。具体配置参考 README

![image](https://user-images.githubusercontent.com/61240774/206885211-d878dd1e-df00-4d8d-ae98-d3a074c1a582.png)
